//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace script
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACR_PERSONAL_INFO
    {
        public decimal ID { get; set; }
        public Nullable<decimal> MARITAL_STATUS { get; set; }
        public Nullable<decimal> CHILD_NO { get; set; }
        public Nullable<decimal> SENIORITY_POSITION { get; set; }
        public Nullable<System.DateTime> JOINING_GOVT { get; set; }
        public Nullable<System.DateTime> JOINING_GADGETED { get; set; }
        public Nullable<System.DateTime> JOINING_CADRE { get; set; }
        public Nullable<System.DateTime> JOINING_CURRENT_POST { get; set; }
        public Nullable<decimal> PAY_SCALE_ID { get; set; }
        public Nullable<decimal> CURRENT_BASIC_PAY { get; set; }
        public string ACADEMIC_QUALIFICATION { get; set; }
        public string TRAINING_HOME { get; set; }
        public string TRAINING_ABROAD { get; set; }
        public string FOREIGN_LANG_SPEAKING { get; set; }
        public string FOREIGN_LANG_READING { get; set; }
        public string FOREIGN_LANG_WRITING { get; set; }
        public Nullable<System.DateTime> ACR_START { get; set; }
        public Nullable<System.DateTime> ACR_END { get; set; }
        public Nullable<decimal> ACR_TYPE { get; set; }
        public System.DateTime REPORING_DATE { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public Nullable<decimal> UPDATED_BY { get; set; }
        public decimal PROFILE_ID { get; set; }
        public decimal ACR_YEAR { get; set; }
    }
}
