//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace script
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACR_CONSIDERATION
    {
        public decimal ID { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal PROFILE_ID { get; set; }
        public decimal ACR_PERSONAL_INFO_ID { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public Nullable<decimal> UPDATED_BY { get; set; }
    }
}
