//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace script
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACR_WORK_DETAIL
    {
        public decimal ID { get; set; }
        public decimal PROFILE_ID { get; set; }
        public decimal ACR_YEAR { get; set; }
        public decimal ACR_MASTER_ID { get; set; }
        public Nullable<decimal> PROFESSIONAL_KNOWLEDGE { get; set; }
        public Nullable<decimal> WORK_QUALITY { get; set; }
        public Nullable<decimal> COMPLETED_WORK_QUANTITY { get; set; }
        public Nullable<decimal> SUPERVISION_CAPABILITY { get; set; }
        public Nullable<decimal> RELATION_WITH_COLLEGUE { get; set; }
        public Nullable<decimal> DECISION_MAKING { get; set; }
        public Nullable<decimal> DECISION_IMPLEMENTATION { get; set; }
        public Nullable<decimal> TRAINING_CAPABILITY { get; set; }
        public Nullable<decimal> EXPRESSIBILITY_WRITING { get; set; }
        public Nullable<decimal> EXPRESSIBILY_SPEAKING { get; set; }
        public Nullable<decimal> INTEREST_IN_ACR { get; set; }
        public Nullable<decimal> DUTIFULLNESS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public Nullable<decimal> UPDATED_BY { get; set; }
    }
}
