//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace script
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACR_PERSONAL_DETAIL
    {
        public decimal ID { get; set; }
        public decimal PROFILE_ID { get; set; }
        public decimal ACR_YEAR { get; set; }
        public Nullable<decimal> DISCIPLINE { get; set; }
        public Nullable<decimal> JUDGEMENT { get; set; }
        public Nullable<decimal> IQ { get; set; }
        public Nullable<decimal> ENTHUSIASM { get; set; }
        public Nullable<decimal> PERSONALITY { get; set; }
        public Nullable<decimal> COOPERATION { get; set; }
        public Nullable<decimal> TIMELINESS { get; set; }
        public Nullable<decimal> RELIABILITY { get; set; }
        public Nullable<decimal> RESPONSIBILITY { get; set; }
        public Nullable<decimal> INTEREST_IN_WORK { get; set; }
        public Nullable<decimal> ACTIVITY_IN_DUTY { get; set; }
        public Nullable<decimal> SECURITY_AWARENESS { get; set; }
        public Nullable<decimal> BEHAVIOUR { get; set; }
    }
}
