//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace script
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACR_HEALTH
    {
        public decimal ID { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string VISION { get; set; }
        public string BLOOD_GROUP { get; set; }
        public Nullable<decimal> BLOOD_PRESSURE_SISTOL { get; set; }
        public Nullable<decimal> BLOOD_PRESSURE_DIASTOL { get; set; }
        public string ECG_REPORT { get; set; }
        public string MEDICAL_CLASSIFICATION { get; set; }
        public string DISABILITIES { get; set; }
        public Nullable<System.DateTime> REPORT_DATE { get; set; }
        public string HEALTH_OFFICER_NAME { get; set; }
        public string HEALTH_OFFICER_DESIGNATION { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public decimal PROFILE_ID { get; set; }
        public decimal ACR_YEAR { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public Nullable<decimal> UPDTAED_BY { get; set; }
    }
}
