//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace script
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACR_MASTER
    {
        public decimal ID { get; set; }
        public decimal ACR_YEAR { get; set; }
        public decimal PROFILE_ID { get; set; }
        public decimal SUPERVISOR_ID { get; set; }
        public decimal APPROVER_ID { get; set; }
        public Nullable<decimal> TOTAL_SUPERVISOR { get; set; }
        public decimal IS_BACK { get; set; }
        public Nullable<decimal> TOTAL_APPROVED { get; set; }
        public decimal IS_TOTAL_ONLY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDTAED_ON { get; set; }
        public Nullable<decimal> UPDTAED_BY { get; set; }
        public Nullable<decimal> STATUS { get; set; }
    }
}
