//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace script
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACRDBContext : DbContext
    {
        public ACRDBContext()
            : base("name=ACRDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACR_CONSIDERATION> ACR_CONSIDERATION { get; set; }
        public DbSet<ACR_HEALTH> ACR_HEALTH { get; set; }
        public DbSet<ACR_MASTER> ACR_MASTER { get; set; }
        public DbSet<ACR_PERSONAL_DETAIL> ACR_PERSONAL_DETAIL { get; set; }
        public DbSet<ACR_PERSONAL_INFO> ACR_PERSONAL_INFO { get; set; }
        public DbSet<ACR_WORK_DETAIL> ACR_WORK_DETAIL { get; set; }
    }
}
