//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace script
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicant_district
    {
        public applicant_district()
        {
            this.applicant_upazila = new HashSet<applicant_upazila>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int division_id { get; set; }
    
        public virtual applicant_division applicant_division { get; set; }
        public virtual ICollection<applicant_upazila> applicant_upazila { get; set; }
    }
}
