//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace script
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicant_division
    {
        public applicant_division()
        {
            this.applicant_district = new HashSet<applicant_district>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<applicant_district> applicant_district { get; set; }
    }
}
