//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace script
{
    using System;
    using System.Collections.Generic;
    
    public partial class district
    {
        public district()
        {
            this.upazilas = new HashSet<upazila>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int zone_id { get; set; }
    
        public virtual zone zone { get; set; }
        public virtual ICollection<upazila> upazilas { get; set; }
    }
}
