//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace script
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dshe_reqruitmentEntitiesNew : DbContext
    {
        public dshe_reqruitmentEntitiesNew()
            : base("name=dshe_reqruitmentEntitiesNew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<applicant_district> applicant_district { get; set; }
        public DbSet<applicant_division> applicant_division { get; set; }
        public DbSet<applicant_upazila> applicant_upazila { get; set; }
        public DbSet<university> universities { get; set; }
    }
}
