//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace script
{
    using System;
    using System.Collections.Generic;
    
    public partial class upazila
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> district_id { get; set; }
    
        public virtual district district { get; set; }
    }
}
